-- MySQL Script generated by MySQL Workbench (Editado posteriormente)
-- sex 23 set 2022 21:38:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` ENUM("cpf", "cnpj") NOT NULL,
  `identificacao` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identificacao_UNIQUE` (`identificacao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_veiculo_cliente_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identificacao` VARCHAR(125) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deixado_para_analise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deixado_para_analise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM("pendente", "os-aberta", "sem-os") NOT NULL,
  `equipe_id` INT NOT NULL,
  `veiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_deixado_para_analise_equipe1_idx` (`equipe_id` ASC) VISIBLE,
  INDEX `fk_deixado_para_analise_veiculo1_idx` (`veiculo_id` ASC) VISIBLE,
  CONSTRAINT `fk_deixado_para_analise_equipe1`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `mydb`.`equipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deixado_para_analise_veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `mydb`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_do_servico_requisitado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_do_servico_requisitado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(125) NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(125) NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  `valor` FLOAT NOT NULL,
  `tipo_do_servico_requisitado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servico_tipo_do_servico_requisitado1_idx` (`tipo_do_servico_requisitado_id` ASC) VISIBLE,
  CONSTRAINT `fk_servico_tipo_do_servico_requisitado1`
    FOREIGN KEY (`tipo_do_servico_requisitado_id`)
    REFERENCES `mydb`.`tipo_do_servico_requisitado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordem_de_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordem_de_servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `deixado_para_analise_id` INT NOT NULL,
  `status` ENUM("pendente-aprovacao", "aprovado", "realizado", "cancelado") NOT NULL,
  `numero_os` VARCHAR(30) NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_de_entrega` DATE NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ordem_de_servico_deixado_para_analise1_idx` (`deixado_para_analise_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_de_servico_deixado_para_analise1`
    FOREIGN KEY (`deixado_para_analise_id`)
    REFERENCES `mydb`.`deixado_para_analise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pecas_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pecas_material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(125) NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mecanico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(125) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `especialidade` VARCHAR(75) NOT NULL,
  `equipe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mecanico_equipe1_idx` (`equipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_mecanico_equipe1`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `mydb`.`equipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deixado_para_analise_tem_tipo_do_servico_requisitado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deixado_para_analise_tem_tipo_do_servico_requisitado` (
  `deixado_para_analise_id` INT NOT NULL,
  `tipo_do_servico_requisitado_id` INT NOT NULL,
  PRIMARY KEY (`deixado_para_analise_id`, `tipo_do_servico_requisitado_id`),
  INDEX `fk_deixado_para_analise_has_tipo_do_servico_requisitado_tip_idx` (`tipo_do_servico_requisitado_id` ASC) VISIBLE,
  INDEX `fk_deixado_para_analise_has_tipo_do_servico_requisitado_dei_idx` (`deixado_para_analise_id` ASC) VISIBLE,
  CONSTRAINT `fk_deixado_para_analise_has_tipo_do_servico_requisitado_deixa1`
    FOREIGN KEY (`deixado_para_analise_id`)
    REFERENCES `mydb`.`deixado_para_analise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deixado_para_analise_has_tipo_do_servico_requisitado_tipo_1`
    FOREIGN KEY (`tipo_do_servico_requisitado_id`)
    REFERENCES `mydb`.`tipo_do_servico_requisitado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordem_de_servico_relacao_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordem_de_servico_relacao_servico` (
  `ordem_de_servico_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  `status` ENUM("realizado", "pendente") NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`ordem_de_servico_id`, `servico_id`),
  INDEX `fk_ordem_de_servico_has_servico_servico1_idx` (`servico_id` ASC) VISIBLE,
  INDEX `fk_ordem_de_servico_has_servico_ordem_de_servico1_idx` (`ordem_de_servico_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_de_servico_has_servico_ordem_de_servico1`
    FOREIGN KEY (`ordem_de_servico_id`)
    REFERENCES `mydb`.`ordem_de_servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_de_servico_has_servico_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `mydb`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordem_de_servico_relacao_pecas_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordem_de_servico_relacao_pecas_material` (
  `ordem_de_servico_id` INT NOT NULL,
  `pecas_material_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`ordem_de_servico_id`, `pecas_material_id`),
  INDEX `fk_ordem_de_servico_has_pecas_material_pecas_material1_idx` (`pecas_material_id` ASC) VISIBLE,
  INDEX `fk_ordem_de_servico_has_pecas_material_ordem_de_servico1_idx` (`ordem_de_servico_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_de_servico_has_pecas_material_ordem_de_servico1`
    FOREIGN KEY (`ordem_de_servico_id`)
    REFERENCES `mydb`.`ordem_de_servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_de_servico_has_pecas_material_pecas_material1`
    FOREIGN KEY (`pecas_material_id`)
    REFERENCES `mydb`.`pecas_material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cobranca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cobranca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `data_limite_pagamento` DATE NOT NULL,
  `data_pagamento_realizado` DATE NULL,
  `ordem_de_servico_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cobranca_ordem_de_servico1_idx` (`ordem_de_servico_id` ASC) VISIBLE,
  UNIQUE INDEX `ordem_de_servico_id_UNIQUE` (`ordem_de_servico_id` ASC) VISIBLE,
  CONSTRAINT `fk_cobranca_ordem_de_servico1`
    FOREIGN KEY (`ordem_de_servico_id`)
    REFERENCES `mydb`.`ordem_de_servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
